# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60afedf10f5c5f7a56d3bcc7fdcbb70697a0b87470f2e84c69afc1dc588ecd08a3622c8d9f9b7960de77de7c2ed067689e454db0c57118475fb9db438907d31a

test:
  secret_key_base: 0665a784948d4f3ff2cdb641655a51a63d86680e1c591ceafb17e2b7731842009e757a5eea28b05b1b60de67bf4c06b6ad6f67ef7a8e1722f9c17e73a7899caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
